dist: trusty
language: python

python:
    - 3.4
    - 3.5
    - 3.6
    - nightly

install:
    - pip install coveralls pytest==3.6 pytest-cov pycodestyle nibabel

script:
    - export PYTHONPATH=${PYTHONPATH}:${PWD}
    - pycodestyle sam/imageutils.py tests/*.py
    - pytest --cov=sam ./

after_success:
    - coveralls
